### ISSUE TITLE
OpenSearch for packages returns None domain

### ISSUE THREAD

**Issue by teh-banana** [archlinux/archweb#541]
When adding the OpenSearch for [Arch Linux - Package Search](https://archlinux.org/packages/) page into my web browser (Firefox) it will result in attempting to search the `None` domain instead of `archlinux.org`.

The OpenSearch URL is [located here](https://archlinux.org/opensearch/packages/). Downloading the page / viewing source shows all the domains as `None`.

**Comment by jelly** [comment]
Ah, seems `domain` is now `None`:

```
	<Url type="text/html" template="{{ domain }}/packages/?q={searchTerms}"/>
```

This could be a django 5.1 change

**Comment by jelly** [comment]
So that comes from:

```
    domain = "%s://%s" % (request.scheme, request.META.get('HTTP_HOST'))

    return render(request, 'packages/opensearch.xml',
                  {'domain': domain},
                  content_type='application/opensearchdescription+xml')
```

**Comment by jelly** [comment]
And nginx never seems to pass HTTP_HOST so this is more a configuration issue in nginx.

**Comment by teh-banana** [comment]
Thanks for working on this, I just tried to add it again as I noticed it was updated on the site and now I get the following error:

> Firefox could not download the search plugin from: https://archlinux.org/opensearch/packages/

![Image](https://github.com/user-attachments/assets/438896b3-2d4f-4bc0-8dca-9b4d2b8bc3da)

Not sure if its because the opensearch just has `archlinux.org` and does not include `https://`

**Comment by jelly** [comment]
Thanks for testing this! Looking at the mediawiki output, it indeed seems to lack https://


https://wiki.archlinux.org//api.php?action=opensearch&format=xml&search=Te

**Comment by jelly** [comment]
@teh-banana can you retry, I've deployed a hotfix on our production server.

**Comment by teh-banana** [comment]
It is still currently failing, although I did some looking into it myself a bit more. It is still missing some `https://` that are required. I was able to get it to work on a local test by adding the protocol in this `<Url type="text/html" template="archlinux.org/packages/?q={searchTerms}"/>` tag. Though when not including it for the `<Image>` tags too, there will be no icon for the search in the settings page and when including it for those tags too it works.

Also can confirm the 2 that now have the protocol also require it, as it will fail without them too.

**Comment by Exagone313** [comment]
If you look at the patch from df4b0bfd678ac8d9a1dc8fbbe3500115d0b0d89a you can see that `request.scheme` was removed from the `domain` variable.

The fix is probably something like this (not sure if `request.scheme` really contains the end-user protocol and not the protocol used between archweb and nginx - and not sure if the test passes):

```diff
diff --git a/packages/tests/test_search.py b/packages/tests/test_search.py
index 2915a630..cccfea5b 100644
--- a/packages/tests/test_search.py
+++ b/packages/tests/test_search.py
@@ -67,7 +67,7 @@ def test_sort(client, package):
 def test_packages(client, package):
     response = client.get('/opensearch/packages/')
     assert response.status_code == 200
-    assert 'template="example.com/opensearch/packages/"' in response.content.decode()
+    assert 'template="http://example.com/opensearch/packages/"' in response.content.decode()
 
 
 def test_packages_suggest(client, package):
diff --git a/packages/views/__init__.py b/packages/views/__init__.py
index 50c27839..f7df57e3 100644
--- a/packages/views/__init__.py
+++ b/packages/views/__init__.py
@@ -25,7 +25,7 @@ def opensearch(request):
     current_site = Site.objects.get_current()
 
     return render(request, 'packages/opensearch.xml',
-                  {'domain': current_site.domain},
+                  {'domain': f'{request.scheme}/{current_site.domain}',
                   content_type='application/opensearchdescription+xml')
 
 
diff --git a/public/views.py b/public/views.py
index 17e39971..b82bcc46 100644
--- a/public/views.py
+++ b/public/views.py
@@ -31,7 +31,7 @@ def updates():
         'news_updates': News.objects.order_by('-postdate', '-id')[:15],
         'pkg_updates': updates,
         'staff_groups': StaffGroup.objects.all(),
-        'domain': current_site.domain,
+        'domain': f'{request.scheme}/{current_site.domain}',
     }
     return render(request, 'public/index.html', context)
 
```

**Comment by jelly** [comment]
Thanks for the suggestion, I'll deploy https://github.com/archlinux/archweb/pull/560 today

**Comment by teh-banana** [comment]
Confirmed that this is now working for me in Firefox!
